### ISSUE TITLE
46. show avc sd-service info summary

### ISSUE THREAD

**Issue by q28xp** [networktocode/genieparser#117]
```
sw2#show avc sd-service info summary
Status: CONNECTED

Device ID: sd-sw2.lab.com
Device segment name: core-pop 
Device address: 10.18.29.33

Active controller:
   Type  : Primary
   IP    : 10.11.236.21
   Status: Connected
   Last connection: 18:42:02.000 UTC Fri Oct 2 2020

```
```
ewlc1#show avc sd-service info summary
SD-AVC is disabled
```
```
ewlc3#show avc sd-service info summary 
Status: DISCONNECTED

Device ID: 
Device segment name: global (default)
Device address: 0.0.0.0

Controller address isn't configured
```

**Comment by robschn** [comment]
`^Status: (?P<status>CONNECTED|DISCONNECTED)\s+Device ID: (?P<device_id>\S+)\s+Device segment name: (?P<device_segment_name>\S+)\s+Device address: (?P<device_ipv4_address>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+Active controller:\s+Type\s+: (?P<active_controller_type>\S+)\s+IP\s+: (?P<active_controller_ipv4_address>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+Status: (?P<active_controller_status>\S+)\s+Last connection: (?P<active_contoller_last_connection>.+)$`
