### ISSUE TITLE
56. show  lisp   instance-id * ethernet server

### ISSUE THREAD

**Issue by q28xp** [networktocode/genieparser#142]
[wlc-lipsinst.txt](https://github.com/networktocode/genieparser/files/5431711/wlc-lipsinst.txt)

**Comment by robschn** [comment]
`(?P<last_register>\S+)\s+(?P<up>\S+)\s+(?P<who_last_registered>\d+\.\d+\.\d+\.\d+\:\d+)\s+(?P<inst_id>\d+)\s+(?P<eid_prefix>\S+\.\S+\.\S+/\d+)`

**Comment by robschn** [comment]
`(?P<site_name>\S+)\s+(?P<last_register>never)\s+(?P<up>no)\s+(?P<who_last_registered>\-\-)\s+(?P<inst_id>\d+)\s+(?P<eid_prefix>any-mac)`

`(?P<site_name>\S+)\s+never\s+no\s+\-\-\s+\d+\s+any-mac`

**Comment by robschn** [comment]
`(?P<site_name>|\S+)\s+(?P<last_register>\S+)\s+(?P<up>\S+)\s+(?P<who_last_registered>\-\-|\d+\.\d+\.\d+\.\d+\:\d+)\s+(?P<inst_id>\d+)\s+(?P<eid_prefix>any\-mac|\S+\.\S+\.\S+\d+)`
